### ISSUE TITLE
could you explain this project please?

### ISSUE THREAD

**Issue by cryptowilliam** [tsuz/go-pine#13]
I am researching pine script, your project seems interesting but also confusing. What is the intention of this project? Thank you.

**Comment by tsuz** [comment]
@cryptowilliam 
I used to test my strategy on TradingView and build an arbitrage bot. I needed to quickly move my scripts over while I had the edge ;)  Today, there seems to be quicker solutions like 3commas that can be run from the TradingView UI. 

I'd be open to suggestions.
